Cocktail.destroy_all
Ingredient.destroy_all
Cocktail.create(name: "Mint Julep")
Cocktail.create(name: "Whiskey Sour")
Cocktail.create(name: "Mojito")
Cocktail.create(name: "Jumpig Jack")
Cocktail.create(name: "Long Island Eis Tea")
Cocktail.create(name: "Zombie")
Cocktail.create(name: "Sex on the Beach")
Cocktail.create(name: "Hopper")
Cocktail.create(name: "Gin Tonic")
Cocktail.create(name: "Lemon Slasher")
Cocktail.create(name: "Madame la Rouge")
Cocktail.create(name: "Blody Marie")

Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "tonic")
Ingredient.create(name: "coca cola")
Ingredient.create(name: "red bull")
Ingredient.create(name: "fruit mix")
Ingredient.create(name: "cream")
Ingredient.create(name: "pineaple")
